[package]
name = "egui-deadlock"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.19.0"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }

[profile.dev]
codegen-units = 1